export const REGISTER = "REGISTER";
export const CREATE_POST = "CREATE_POST";
export const EDIT_POST = "EDIT_POST";
export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_HOT_POSTS = "FETCH_HOT_POSTS";
export const FETCH_POST = "FETCH_POSTS";
export const DELETE_POST = "DELETE_POST";
export const RESET_POST = "RESET_POST";
export const TRIGGER_SEARCH_POSTS_ON = "TRIGGER_SEARCH_POSTS_ON"  // Under some circumstances, we need to trigger the search again, eg: After creating a new post.
export const TRIGGER_SEARCH_POSTS_OFF = "TRIGGER_SEARCH_POSTS_OFF"